data conversion: qed-c to stochastic benchmark
usra-riacs/stochastic-benchmark pull request #22
Opened 2023-01-31 23:08 UTC by PratikSathe

2023-02-03 00:50 UTC, bernalde commented
Pratik, do we need to have all the data in the repository or can we have an example file/compressed folder and have only one or two as an example? We are generating intermediate files for the analysis anyways.
Let me know what you think about this.

2023-02-08 19:42 UTC, PratikSathe commented
I have removed the json files.

2023-02-08 21:51 UTC, bernalde requested changes
Thanks for your PR Pratik; please address the comments.

2023-02-08 21:51 UTC, bernalde commented on examples/QEDC_to_WS_conversion/conversion.py
> +# maxcut_style = os.path.join('..', '..', '_common', 'maxcut.mplstyle')
If these comments are not used, better remove them.

2023-02-08 21:51 UTC, bernalde commented on examples/QEDC_to_WS_conversion/conversion.py
> +    """_summary_
This is not quite documented. Please complete this

2023-02-08 21:51 UTC, bernalde commented on examples/QEDC_to_WS_conversion/conversion.py
> +    """_summary_
See comment above

2023-02-08 21:51 UTC, bernalde commented on examples/QEDC_to_WS_conversion/conversion.py
> +    return df
Add extra empty line here

2023-02-08 23:27 UTC, PratikSathe commented on examples/QEDC_to_WS_conversion/conversion.py
> +# maxcut_style = os.path.join('..', '..', '_common', 'maxcut.mplstyle')
Addressed now

2023-02-08 23:27 UTC, PratikSathe commented on examples/QEDC_to_WS_conversion/conversion.py
> +    """_summary_
Addressed now

2023-02-08 23:27 UTC, PratikSathe commented on examples/QEDC_to_WS_conversion/conversion.py
> +    """_summary_
Addressed now

2023-02-08 23:27 UTC, PratikSathe commented on examples/QEDC_to_WS_conversion/conversion.py
> +    return df
Addressed now

2023-02-08 23:28 UTC, PratikSathe commented
Comments have been addressed in a new commit.

2023-02-09 00:50 UTC, bernalde approved these changes

2023-02-09 00:51 UTC, merged